# Netlify Configuration

[build]
  publish = "."
  command = "echo 'Static site - no build required'"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-Robots-Tag = "index, follow, max-snippet:-1, max-image-preview:large"

# HTML Cache
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache static assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/png"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/x-icon"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/svg+xml; charset=utf-8"

# Sitemap header - ensure proper content type for Google
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"

# RSS header
[[headers]]
  for = "/rss.xml"
  [headers.values]
    Content-Type = "application/rss+xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"

# Robots.txt header
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=86400"

# Manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
    Cache-Control = "public, max-age=86400"

# SEO-friendly redirects
[[redirects]]
  from = "/bmi"
  to = "/"
  status = 301

[[redirects]]
  from = "/calculator"
  to = "/"
  status = 301

[[redirects]]
  from = "/bmi-calculator"
  to = "/"
  status = 301

[[redirects]]
  from = "/body-mass-index"
  to = "/"
  status = 301

[[redirects]]
  from = "/health-calculator"
  to = "/"
  status = 301

[[redirects]]
  from = "/weight-calculator"
  to = "/"
  status = 301

[[redirects]]
  from = "/index"
  to = "/"
  status = 301

# File extension redirects
[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/robots"
  to = "/robots.txt"
  status = 301

# Force HTTPS
[[redirects]]
  from = "http://free-bmi-calculator.netlify.app/*"
  to = "https://free-bmi-calculator.netlify.app/:splat"
  status = 301
  force = true

# SPA fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
